### ISSUE TITLE
Passwords are not working.

### ISSUE THREAD

**Issue by Galen-dp** [MahStudio/WSLackware#10]
Hi,

First thank you for setting up WSLackware. I was hoping someone would do this.

I just installed the latest version of Windows 10 (Ver: 21H2 Build: 19044.1526) onto a laptop. I was able to get WSLackware (V15.0.18)  and Ubuntu both installed on WSL. During the install of WSLackware I was not asked for a user name or passwrod. I was asked for a user name and password installing Ubuntu.

 When I run wsl I default to root without a password. I set a password for root yet wsl goes straight to the bash shell. I also added a user and set a password. Same thing. wsl --user <username> also goes straight to the bash shell.

Have I done something wrong here?

**Comment by RezaT4795** [comment]
What package did you install? The "tar.gz" or the "appxbundle"?

By the way, if you mean that you want to be able to login with `wsl --user` using your password, I'm afraid WSL doesn't support that, all distros go straight to bash without password. The password you set for your user is meant be used for sudo operations. But you can't use it to start your wsl distro, like you do on a real linux machine.

**Comment by RSKYS** [comment]
If you use appxbundle, there's simple trick:
Copy configurations of generated $USER under /root/
Once you did, close and re-open and remove default user.

Now it will lead you to root shell# everytime, no password, not even password when you perform su commands.
Easy pisy
