### ISSUE TITLE
man command doesnt work

### ISSUE THREAD

**Issue by gcecchi** [MahStudio/WSLackware#12]
Hi, great work.
Installed V15.0.19 in wsl2 with 
wsl.exe --import WSlackware c:\WSlackware .\install.tar.gz
running man commands gives error:
man: error while loading shared libraries: libseccomp.so.2: cannot open shared object file: No such file or directory

solved with 
slackpkg install libseccomp

Gianluca

**Comment by RezaT4795** [comment]
@gcecchi Thank you for using WSLackware. We'll add this package to the next release.

Reza
