### ISSUE TITLE
Certificate's original date prevents a reinstall

### ISSUE THREAD

**Issue by DoctorWho8** [MahStudio/WSLackware#14]
I needed to reinstall the whole business. I found that by using the Powershell scripts the system complained that the date on the computer did not agree with the date (enclosed) in the certificate. It therefore prevented installing that way. I then used the second method to install the whole business. We need a better certificate creation method that would allow this. I'm not even sure it would work again  say if I needed to say install Windows all over again onto the system.

**Comment by DoctorWho8** [comment]
It has been a month plus several days since opening. Isn't anyone else going to comment, and ask what the <BLEEP!> I am talking about up there?

**Comment by RezaT4795** [comment]
@DoctorWho8 Thanks for using WSLackware. Unfortunately me and @Mohsens22 were extremely busy in the past year and couldn't make time for this side project. But there's nothing to worry about.
Expect a new update this weekend.

**Comment by RezaT4795** [comment]
@DoctorWho8 You can download and enjoy the new update.
