### ISSUE TITLE
Installation of WSLackware fails on an odd error with an even stranger description which fails to explain how to correct it

### ISSUE THREAD

**Issue by DoctorWho8** [MahStudio/WSLackware#15]
Okay I needed to reinstall WSlackware again and followed the same steps I used the first time around. (For installing Windows here that is.) I instructed the OS to expload the package and start the installation process. The first time it failed and said this:
"App installation failed with error message: An internal error occurred with error 0x80073D05. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80073d05)" I actually did look things up. The explanation naturally did not make sense. Then I uninstalled everything to do with WSL from the updates and the things that the app functions thing said I could, and also the function that enables it from the perspective of the computer, including the HyperV control panel and so-forth. I thenb tried again and ended with the same message. The response is: "ERROR_DELETING_EXISTING_APPLICATIONDATA_STORE_FAILED | 0x80073D05 | An error occurred while deleting the package's previously existing application data.You can get this error if the simulator is running. Close the simulator. You can also get this error if there are files open in the app data (for example, if you have a log file open in a text editor)."

I have looked in the Event Viewer. Nothing there explains what happened. Help please?

**Comment by RezaT4795** [comment]
#16
