### ISSUE TITLE
Installation Fails from Store in Windows 11

### ISSUE THREAD

**Issue by ahwm** [MahStudio/WSLackware#17]
Fresh Windows 11 computer, installed WSlackware from the Microsoft Store and got this error message:

![image](https://github.com/user-attachments/assets/9fa7482c-4eb6-4dc3-b463-598d81c7d095)

I've verified that WSL is enabled. Any ideas?

**Comment by RezaT4795** [comment]
@ahwm Hi, Thanks for using WSLackware. You need to install WSL2 kernel update. You can either install it using Windows Update or [Download it from Microsoft](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi).
