### ISSUE TITLE
I followed both install methods for the current release

### ISSUE THREAD

**Issue by DoctorWho8** [MahStudio/WSLackware#8]
Hello!
I followed both install methods. That is I used the Powershell scripts secondly, and the WSL install methods. For the Powershell methods, I needed to enable the developer modules, that worked. So did the WSL install methods.

But, ah, I did not get the user experience that happens when installing the others especially SuSe first and then those Debian ones because those are the only Microsoft recognises for building a new kernel from source code. I must have done something wrong.

**Comment by RezaT4795** [comment]
I'm not sure what you mean by "user experience". Please give me more details about your issue.

**Comment by DoctorWho8** [comment]
Normally when a distribution is packaged for working under WSL, the installer launches a process that both creates that VHD and then starts a script which is explains that the user needs to create a user name and of course a password. The root user also sometimes gets assigned a paswword. I confess that normally using Slackware on a regular X86 platform, I do not create a user, and continue along working as root.  In this case that didn't happen. I had hoped that using the Powershell scripts would do that. Also I only see the Icon when launching from the starter, not from the Powershell prompt using the wsl command. However lacking all of this does not drag from the experience of seeing Slackware running under the WSL process.

My only problem is one of creating a user. I think I can work that out by myself, but it's not needed now.

**Comment by RezaT4795** [comment]
> Normally when a distribution is packaged for working under WSL, the installer launches a process that both creates that VHD and then starts a script which is explains that the user needs to create a user name and of course a password. The root user also sometimes gets assigned a paswword. I confess that normally using Slackware on a regular X86 platform, I do not create a user, and continue along working as root.  In this case that didn't happen. I had hoped that using the Powershell scripts would do that. Also I only see the Icon when launching from the starter, not from the Powershell prompt using the wsl command. However lacking all of this does not drag from the experience of seeing Slackware running under the WSL process.
> 
> My only problem is one of creating a user. I think I can work that out by myself, but it's not needed now.

Using the appx file or even powershell scripts, does create a user. It'll only start with a root account if you import "install.tar.gz" manually.

**Comment by DoctorWho8** [comment]
Now that we have that issue settled. There's another, but that's for a new issue. I'm closing one and marking it as done.
